# Generated by Django 4.0.4 on 2022-06-28 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='')),
                ('description', models.TextField(verbose_name='')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='')),
                ('description', models.TextField(verbose_name='')),
                ('status', models.CharField(choices=[('PLANNED', 'Запланированно'), ('PROCESS', 'В процессе'), ('DONE', 'Завершено')], default='PLANNED', max_length=50, verbose_name='Статус')),
                ('deadline', models.DateTimeField(verbose_name='')),
                ('category', models.ManyToManyField(related_name='todo', to='api.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
            },
        ),
    ]
